// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSWq713iiHtxfjyXnFRjKP1wbHYh5YeSk',
    appId: '1:218305321136:web:7eecfe95615965978b0375',
    messagingSenderId: '218305321136',
    projectId: 'agroalerta-840ff',
    authDomain: 'agroalerta-840ff.firebaseapp.com',
    storageBucket: 'agroalerta-840ff.firebasestorage.app',
    measurementId: 'G-SHQSM5DM8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPxFnLPbrxnYDaZxu9Zk0QuO_vvik0kLQ',
    appId: '1:218305321136:android:cf54e28bea5c2f5b8b0375',
    messagingSenderId: '218305321136',
    projectId: 'agroalerta-840ff',
    storageBucket: 'agroalerta-840ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxHxpsfkWr2mLe_5hEn4_7yplC7fEyhlw',
    appId: '1:218305321136:ios:2ac44d8f3326a3008b0375',
    messagingSenderId: '218305321136',
    projectId: 'agroalerta-840ff',
    storageBucket: 'agroalerta-840ff.firebasestorage.app',
    iosBundleId: 'com.example.agroalertaAndalucia',
  );
}
